Map<String, String> ErrorJson = {
  "1000": "sucesso",
  "1001": "Solicitações filtradas de downgrade",
  "1002": "Restrições geográficas",
  "1003": "Token expirado",
  "1004": "usuário duplicado",
  "1005": "O nível do usuário é muito baixo",
  "1006": "bloqueado",
  "1007": "nome de usuário ou senha errados",
  "1008": "Senha muito fraca",
  "1009": "Usuário não existe",
  "1010": "Muitas falhas de login",
  "1011": "O arquivo de upload é muito grande",
  "1012": "As apostas na loteria excedem o número máximo de apostas",
  "1013": "erro no sistema %s",
  "1014": "Por favor, complete a autenticação de nome real primeiro",
  "1015": "Por favor, vincule seu telefone primeiro",
  "1016": "A conta não foi autenticada",
  "1017": "atualização do sistema",
  "1018": "Telefone não vinculado",
  "1019": "Erro no código de verificação",
  "1020": "conta está suspensa",
  "1021": "Saldo insuficiente",
  "1022": "permissão negada",
  "1023": "Equilíbrio insuficiente no local",
  "1024": "parâmetro está vazio",
  "1025": "Erro de parâmetro",
  "1026": "A senha original está errada",
  "1027": "tipo de dispositivo errado",
  "1028": "Erro de redis %s",
  "1029": "As duas senhas não combinam",
  "1030": "erro de banco de dados%s",
  "1031": "Erro na conta, digite novamente",
  "1032": "Manutenção do local",
  "1033": "erro de transferência de local",
  "1034": "erro de transferência de local",
  "1035": "Consulta de erro de saldo",
  "1036": "O status do pedido é anormal",
  "1037": "local não existe",
  "1038": "O formato do arquivo é inválido",
  "1039": "A cota excede o limite",
  "1040": "erro de configuração de sessão",
  "1041": "rpc obter erro de informação",
  "1042": "informações de atualização de rpc falharam",
  "1043": "A execução da transação falhou",
  "1044": "Há uma ordem de transferência em andamento",
  "1045": "O local não tem registro de transferência",
  "1046": "Vincule o e-mail primeiro",
  "1047": "Erro no código de verificação, verifique novamente",
  "1048": "Erro de código de verificação de e-mail",
  "1049": "código de verificação deve ser preenchido",
  "1050": "número de celular já existe",
  "1051": "caixa de correio já existe",
  "1052": "O cartão já existe",
  "1053": "limite de gênero",
  "1054": "O aniversário está vinculado",
  "1055": "O nome verdadeiro está vinculado",
  "1056": "sem atualização de dados",
  "1057": "quantidade errada",
  "1058": "pedidos frequentes",
  "1059": "erro de consulta ES%s",
  "1060": "cartão de banco não existe",
  "1061": "canal não existe",
  "1062": "O nome de usuário já existe",
  "1063": "canal já existe",
  "1064": "canal já existe",
  "1065": "canal não existe",
  "1066": "pedido já existe",
  "1067": "pagamento falhou",
  "1068": "Pagamento falhou",
  "1069": "ordem não existe",
  "1070": "erro de análise de formato",
  "1071": "Vincule até 5 cartões bancários",
  "1072": "Falha no registro do local",
  "1073": "Fluxo fora do padrão",
  "1074": "O número de códigos de verificação foi esgotado",
  "1075": "Falha ao enviar o código de verificação",
  "1076": "Falha na solicitação",
  "1077": "Erro de ID do local",
  "1078": "modo de ajuste errado",
  "1079": "Erro múltiplo de rotatividade",
  "1080": "erro de endereço de imagem",
  "1081": "UID errado",
  "1082": "erro do candidato",
  "1083": "erro do revisor",
  "1084": "Erro de status de moderação",
  "1085": "tipo de ajuste errado",
  "1086": "Erro de status do problema",
  "1087": "erro seamo",
  "1088": "Erro de parâmetro de estado",
  "1089": "erro de grupo de usuários",
  "1090": "identidade errada",
  "1091": "O formato da senha está errado [8-20 dígitos, apenas letras e números são suportados, o número da conta e a senha não podem ser iguais, os símbolos não são suportados.]",
  "1092": "erro de ip",
  "1093": "erro de versão",
  "1094": "URL errada",
  "1095": "Erro de formato de observação",
  "1096": "erro de conta bancaria",
  "1097": "formato de hora errado",
  "1098": "erro do dispositivo",
  "1099": "arquivo não existe",
  "1100": "Tipo de carteira errado",
  "1101": "Tipo de bônus errado",
  "1102": "Número de telefone incorreto",
  "1103": "Erro de nome de proxy",
  "1104": "Erro de formato de e-mail",
  "1105": "Erro de etiqueta de membro",
  "1106": "gênero errado",
  "1107": "comprimento de texto errado",
  "1108": "caminho de arquivo errado",
  "1109": "O formato da URL do redirecionamento está errado",
  "1110": "erro de tipo de dispositivo push",
  "1111": "nível de associação errado",
  "1112": "erro do módulo de aplicativo",
  "1113": "A bandeira comumente usada está errada",
  "1114": "erro de cenário de aplicativo",
  "1115": "Valor de classificação incorreto",
  "1116": "Erro no valor da carteira do local",
  "1117": "erro de nome do local",
  "1118": "tipo de jogo errado",
  "1119": "Tipo de ajuste de nível de associação incorreto",
  "1120": "criar erro de nome de usuário",
  "1121": "registro já existe",
  "1122": "registro não existe",
  "1123": "O limite de saque único deve ser menor ou igual ao limite de saque diário único",
  "1124": "erro de tipo de proxy",
  "1125": "Erro de sinalizador de liquidação antecipada",
  "1126": "As observações não podem estar vazias",
  "1127": "id de registro errado",
  "1128": "nome verdadeiro errado",
  "1129": "Operação falhou",
  "1130": "Falha ao obter dados",
  "1131": "Intervalo de tempo de consulta incorreto",
  "1132": "Erro de protocolo de moeda virtual",
  "1133": "O endereço da carteira de moeda virtual está duplicado",
  "1134": "O número de carteiras de moeda virtual excede o limite superior",
  "1135": "tipo de transação errado",
  "1136": "sinalizador de tipo de arquivo incorreto",
  "1137": "Falha no upload do arquivo estático",
  "1138": "Falha na abertura do arquivo",
  "1139": "Erro de condição de consulta",
  "1140": "Erro de tipo irrestrito",
  "1141": "O celular já foi vinculado, por favor, não vincule novamente",
  "1142": "erro de tipo de mudança de conta",
  "1143": "Erro de tipo de transferência de local",
  "1144": "Erro de intervalo de consulta de valor de aposta",
  "1145": "Este membro da tag está em uso",
  "1146": "Erro de ID do comerciante",
  "1147": "nome do canal errado",
  "1148": "Processamento de aplicativo de evento",
  "1149": "São permitidos até três eventos",
  "1150": "Feche antes de excluir eventos",
  "1151": "Não recarregado",
  "1152": "tipo de atividade errado",
  "1153": "Erro de tipo de presente de evento",
  "1154": "erro de nome do destinatário",
  "1155": "O endereço de entrega está errado",
  "1156": "Nome do presente errado",
  "1157": "erro de atributo de presente",
  "1158": "Tipo de solicitação de presente incorreto",
  "1159": "O valor da retirada diária foi limitado, retire amanhã",
  "1160": "O número de saques no dia atingiu o limite máximo, retire amanhã",
  "1161": "erro de código de status",
  "1162": "erro OID",
  "1163": "A nova senha não pode ser igual à senha original, digite-a novamente",
  "1164": "ID do canal errado",
  "1165": "O número de telefone está errado, digite novamente",
  "1166": "E-mail e nome de usuário não correspondem",
  "1167": "Erro de nome de usuário da operação",
  "1168": "tipo financeiro errado",
  "1169": "Tipo de tempo de filtro incorreto",
  "1170": "erro de limite mínimo",
  "1171": "erro de limite máximo",
  "1172": "Os canais em uso não podem ser excluídos",
  "1173": "Existem canais sob o canal que não podem ser excluídos",
  "1174": "O ID do comerciante ou o nome do canal já existe",
  "1175": "id de canal ou id de canal errado",
  "1176": "Código do banco ou nome do banco incorreto",
  "1177": "O nome de usuário do convidador está errado",
  "1178": "Por favor, atualize após o fechamento",
  "1179": "Por favor, feche e exclua",
  "1180": "código de verificação não existe",
  "1181": "Erro de parâmetro de cota",
  "1182": "o canal principal está fechado",
  "1183": "O membro está bloqueado",
  "1184": "quantidade errada do pedido",
  "1185": "erro de id de evento",
  "1186": "O evento está fechado",
  "1187": "Já participou da atividade, não pode se inscrever novamente",
  "1188": "O tempo de resgate do presente expirou",
  "1189": "A atividade foi aberta, feche-a antes de editar",
  "1190": "Erro de título personalizado do evento",
  "1191": "O número de dias do período de validade do resgate da atividade está errado",
  "1192": "O número de dias no período de contagem cumulativa ativo está errado",
  "1193": "Este local não está participando do evento",
  "1194": "Como você enviou pedidos não depositados várias vezes, inicie um depósito após 5 minutos",
  "1195": "Como você enviou vários pedidos não depositados, inicie um depósito após 24 horas",
  "1196": "Sem canal de depósito",
  "1197": "Não é possível excluir o último anúncio",
  "1198": "A aplicação do evento falhou",
  "1199": "equipe já existe",
  "1200": "Erro de formato de senha de proxy",
  "1201": "Só pode revisar ou rejeitar mensagens com revisão pendente",
  "1202": "Somente as mensagens com revisão pendente ou desativadas podem ser ativadas",
  "1203": "O status deve ser habilitado para desabilitar",
  "1204": "Este canal está temporariamente indisponível, tente outro canal ou tente novamente mais tarde",
  "1205": "Atualmente, este canal não suporta a retirada do cartão bancário do membro",
  "1206": "Atualmente não há canais de pagamento disponíveis",
  "1207": "erro humano de desenvolvimento",
  "1208": "erro do mantenedor",
  "1209": "link já existe",
  "1210": "erro de código de verificação dinâmica",
  "1211": "O mesmo agente só pode formar uma equipe",
  "1212": "O agente já é uma sublinha",
  "1213": "Erro na conta do operador",
  "1214": "Erro de conta do agente de encaminhamento",
  "1215": "Número de conta do agente incorreto após a transferência",
  "1216": "Você ainda não tem equipe",
  "1217": "O pedido foi selecionado",
  "1218": "Este membro já é membro do agente %s",
  "1219": "Um máximo de dez membros podem ser adicionados por vez",
  "1220": "Só pode desqualificar agentes que não estão na equipe, remova-os da equipe antes de fazer isso",
  "1221": "Coleta manual, incapaz de ajustar aceitantes de pedidos",
  "1222": "Este agente não pode entrar ou criar uma nova equipe este mês, tente novamente no próximo mês",
  "1223": "Este tipo de conta não pode entrar na equipe",
  "1224": "Agentes oficiais não permitem saques em dinheiro",
  "1225": "Intervalo de valor da taxa de comissão 0-100",
  "1226": "O registro do dispositivo foi banido, entre em contato com o atendimento ao cliente, se necessário",
  "1227": "Desculpe, sua área é restrita. Se você tiver alguma dúvida, entre em contato com o atendimento ao cliente online para consulta",
  "1228": "Nome de usuário incorreto",
  "1229": "Temporariamente incapaz de sacar dinheiro, entre em contato com o atendimento ao cliente",
  "1230": "Seu volume de negócios efetivo não atende aos requisitos temporariamente, continue trabalhando duro！",
  "1231": "Conectado hoje",
  "1232": "Nenhum sinal perdido, não há necessidade de fazer as pazes",
  "1233": "Este cartão foi banido",
  "1234": "O cartão do banco é anormal, entre em contato com o atendimento ao cliente",
  "1235": "sem recompensas disponíveis",
  "1236": "Só pode ser assinado novamente uma vez por semana",
  "1237": "Por favor, liquide todas as comissões antes deste mês antes de dissolver a equipe",
  "1238": "Um cartão bancário que está sendo retirado não pode ser excluído, tente novamente mais tarde",
  "1239": "O tempo de resgate ainda não chegou e o prêmio não pode ser resgatado no momento",
  "1240": "Como você enviou pedidos não depositados várias vezes, inicie um depósito após 30 minutos",
  "1241": "Seu local %s atual completou a rotatividade de %s e você precisa alcançar %s para desbloqueá-lo!",
  "1242": "erro de taxa de câmbio",
  "1243": "O mesmo banco só pode abrir um cartão bancário receptor",
  "1244": "O limite de pagamento do cartão bancário para hoje está cheio, modifique o limite para pagamento de hoje e abra-o",
  "1245": "O hash da transação é inválido",
  "1246": "O nível superior está desabilitado e não pode ser aberto",
  "1247": "Erro de intervalo de desconto",
  "1248": "Configuração de repetição de senha de segurança",
  "1249": "Defina uma senha de segurança primeiro",
  "1250": "A senha de segurança não pode ser igual à senha de login",
  "1251": "Erro de senha de segurança, digite novamente",
  "1252": "Não subordinado diretamente",
  "1253": "O plano de comissão ativo não permite modificação",
  "1254": "Cota insuficiente para um único número",
  "1255": "Número da loteria expirado",
  "1256": "O membro atual tem subordinados",
  "1257": "Já é subordinado do atual agente",
  "1258": "O registro de transferência já existe",
  "1259": "O registro da mensagem na estação expirou",
  "1260": "zalo já existe",
  "1261": "Erro no formato do endereço de entrega",
  "1262": "Já vinculado a zalo, por favor, não vincule novamente",
  "1263": "erro de formato zalo",
  "1264": "A solicitação do serviço de pagamento de três partes falhou",
  "1265": "Lucro negativo não atinge a meta",
  "1266": "O depósito não está de acordo com o padrão",
  "1267": "ordem errada de aplicação",
  "1268": "Você não concluiu a atividade de rotatividade, preencha e inscreva-se novamente",
  "1269": "A vinculação do cartão bancário falhou! Certifique-se de que as informações que você preenche são consistentes e precisas！",
  "1270": "Apenas uma atividade do mesmo tipo pode ser aberta ao mesmo tempo",
  "1271": "O registro de dispositivo único excede o máximo",
  "1272": "O evento expirou",
  "1273": "A verificação por SMS é necessária para o primeiro saque todos os dias",
  "1274": "É proibido editar a taxa de desconto de proxy",
  "1275": "Os níveis superior e inferior têm a mesma autoridade",
  "1276": "Por favor, inscreva-se após 1 da manhã",
  "1277": "Não é permitido excluir cartões bancários da lista negra",
  "1278": "Não é permitido adicionar links promocionais",
  "1279": "A remoção de links promocionais não é permitida",
  "1280": "Não é permitido modificar o desconto/taxa de desconto do subnível",
  "1281": "Falha ao verificar o saldo do local",
  "1282": "Falha no login do local",
  "1283": "Falha ao transferir o local",
  "1284": "falha na transferência do local",
  "1285": "Falha ao verificar a transferência do conhecimento do local",
  "1286": "Local transferido com sucesso",
  "1287": "Falha ao transferir o local",
  "1288": "O local está sendo transferido",
  "1289": "Local transferido com sucesso",
  "1290": "falha na transferência do local",
  "1291": "O local está sendo transferido",
  "1292": "Membro do local expulso falhou",
  "1293": "O pedido foi enviado com sucesso, adicionaremos a cota para você em 5 minutos",
  "1294": "A taxa de câmbio mudou, reenvie as informações de recarga",
  "1295": "O valor que você digitou excede o valor de retirada, por favor, digite novamente",
  "1296": "A senha de segurança que você digitou está errada, digite novamente",
  "1297": "O pedido de saque foi enviado com sucesso, verifique se a conta chegou após 3-5 minutos",
  "1298": "O valor diário de saque em dinheiro foi limitado, retire dinheiro amanhã",
  "1299": "O número de saques em dinheiro no dia atingiu o limite máximo, retire dinheiro amanhã",
  "1300": "Você ainda tem rotatividade de apostas inacabada, por favor, inscreva-se novamente após a conclusão",
  "1301": "A conta ou a senha foram inseridas incorretamente várias vezes, tente novamente após 1 hora ou entre em contato com o atendimento ao cliente online",
  "1302": "A conta foi registrada",
  "1303": "Erro de conta ou senha, digite novamente",
  "1304": "Erro de endereço de moeda virtual",
  "1305": "Tipo errado de transferência de equipe",
  "1306": "As informações do membro não estão completas",
  "1307": "Erro de formato de cartão bancário",
  "1308": "Erro no formato do nome do comerciante",
  "1309": "O comerciante já existe",
  "1310": "O comerciante não existe",
  "1311": "Erro no formato da senha do comerciante",
  "1312": "O e-mail foi vinculado, por favor, não vincule novamente",
  "1313": "O endereço de entrega já foi vinculado, por favor, não o vincule novamente",
  "1314": "erro de tipo de comerciante",
  "1315": "O agente pai não existe",
  "1316": "O tipo de agente não permite modificação da chave do comerciante",
  "1317": "Erro de formato de nome de proxy",
  "1318": "Erro de taxa de taxa",
  "1319": "Erro de status de devolução do pedido",
  "1320": "O cartão não corresponde",
  "1321": "Nenhuma ordem de pagamento correspondente",
  "1322": "Você precisa definir a taxa de taxa do comerciante primeiro",
  "1323": "Tipo de moeda errado",
  "1324": "O primeiro login precisa alterar a senha",
  "1325": "A solicitação falhou, o comerciante foi desativado, entre em contato com o atendimento ao cliente",
  "1326": "Você está proibido de solicitar distribuição, entre em contato com o atendimento ao cliente",
  "1327": "o grupo já existe",
  "1328": "Grupo não existe",
  "1329": "Erro no código de convite, confirme e digite novamente",
  "1330": "bloqueio de conta",
  "1331": "Contas de teste só podem jogar na loteria",
  "1332": "Apenas uma conta de recebimento pode ser aberta ao mesmo tempo",
  "1333": "O número de jogos populares atingiu o limite superior",
  "2000": "falhar",
  "2001": "Pendente",
  "2002": "Em processamento"
};